### ISSUE TITLE
Wrong Input for Neurons in NeuralNetwork

### ISSUE THREAD

**Issue by C0BBL3** [eoriont/machine-learning#17]
You are using the example inputs and outputs given, you not supposed to use this for the neural input, you're supposed to find the input with the weight towards the node from the previous nodes * the activation function of the previous node.

**Comment by eoriont** [comment]
I'm pretty sure that's what I do, however I do admit that it's hardcoded. Since we haven't actually implemented anything other than a 3 node neural network by now and we will inevitably fix this as a class in the future, I'm going to close this.
