### ISSUE TITLE
Weird line break in dataframe

### ISSUE THREAD

**Issue by RileyPaddock** [eoriont/machine-learning#5]
In append_pairwise_interactions in your dataframe you have this weird line break. I don't know if you have a reason but it just seemed off to me. This is the line break
d[new_col] = [x*y for x,
                          y in zip(self.data_dict[x[0]], self.data_dict[x[1]])]

**Comment by eoriont** [comment]
I write code in VSCode with some bizarre python linter that comforms to PEP38, and apparently that line was too long so it broke it into multiple lines in a weird spot. I'll see if I can make it look better

**Comment by eoriont** [comment]
Fix in 5299adf622033ab71d7d8df99bc62efa9eec56d5
